# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]


stages:
  - build
  - test
  - deploy


build:
  stage: build
  script:
    - composer install --no-interaction --no-progress
    - cp .env.example .env
    - vendor/bin/drush cache:rebuild
  artifacts:
    paths:
      - web/sites/default/files


deploy:
  stage: deploy
  script:
    - vendor/bin/drush updb -y
    - vendor/bin/drush cr
